spring:
  datasource:
    url: ${DR_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 28800000
